"""Initial migration for inventory schema

Revision ID: 0d60582209c9
Revises: 
Create Date: 2024-12-13 15:58:57.124562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d60582209c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index('ix_users_email', table_name='users')
#     op.drop_index('ix_users_id', table_name='users')
#     op.drop_index('ix_users_username', table_name='users')
#     op.drop_table('users')
#     op.drop_index('ix_inventory_items_id', table_name='inventory_items')
#     op.drop_index('ix_inventory_items_name', table_name='inventory_items')
#     op.drop_index('ix_inventory_items_sku', table_name='inventory_items')
#     op.drop_table('inventory_items')
#     # ### end Alembic commands ###

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('tread_depth', sa.Float(), nullable=True))
    op.add_column('inventory_items', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###



# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('inventory_items',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('minimum_stock', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='inventory_items_user_id_fkey'),
#     sa.PrimaryKeyConstraint('id', name='inventory_items_pkey')
#     )
#     op.create_index('ix_inventory_items_sku', 'inventory_items', ['sku'], unique=True)
#     op.create_index('ix_inventory_items_name', 'inventory_items', ['name'], unique=False)
#     op.create_index('ix_inventory_items_id', 'inventory_items', ['id'], unique=False)
#     op.create_table('users',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('id', name='users_pkey')
#     )
#     op.create_index('ix_users_username', 'users', ['username'], unique=True)
#     op.create_index('ix_users_id', 'users', ['id'], unique=False)
#     op.create_index('ix_users_email', 'users', ['email'], unique=True)
#     # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'tread_depth')
    op.drop_column('inventory_items', 'weight')
    # ### end Alembic commands ###
