"""Add new fields to inventory_items

Revision ID: d43fbf2cb596
Revises: 0d60582209c9
Create Date: 2024-12-13 16:17:37.379097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd43fbf2cb596'
down_revision: Union[str, None] = '0d60582209c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('model', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('inventory_items', sa.Column('season', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('speed_rating', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('load_index', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('dot', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('warranty_months', sa.Integer(), nullable=True))
    op.add_column('inventory_items', sa.Column('manufacture_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'manufacture_date')
    op.drop_column('inventory_items', 'warranty_months')
    op.drop_column('inventory_items', 'notes')
    op.drop_column('inventory_items', 'image_url')
    op.drop_column('inventory_items', 'dot')
    op.drop_column('inventory_items', 'load_index')
    op.drop_column('inventory_items', 'speed_rating')
    op.drop_column('inventory_items', 'season')
    op.drop_column('inventory_items', 'cost')
    op.drop_column('inventory_items', 'model')
    # ### end Alembic commands ###

